[package]
name = "uor_r4_wasm_bridge"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[dependencies]
wasm-bindgen = "0.2.92"

[profile.release]
opt-level = "z"      # Optimize specifically for minimal binary footprint
lto = true           # Enable Link-Time Optimization
codegen-units = 1    # Force single code-generation unit to allow compiler vectorisation
panic = "abort"      # Strip stack trace unwinding code

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(kani)'] }
