//! # UOR-R4 WebAssembly (WASM) Unified Chat & Training Bridge
//!
//! This module implements a zero-allocation, heap-free, and multiplication-free
//! WASM interface designed to bridge the UOR-R4 cognitive pipeline to modern web browsers.
//! By utilizing `wasm-bindgen`, this bridge exposes high-performance local-first
//! generative inference (the chatbot) and local-first teacher-student gradient alignment
//! (the training harness) directly to HTML5 frontend applications.
//!
//! Strictly compliant with the **Normative CPU-only, Multiplication-free, Zero-allocation Inference Contract (#157)**.

use wasm_bindgen::prelude::*;

// =====================================================================
// 1. CONFIGURATIONS & STATIC METADATA
// =====================================================================

pub const VSA_DIM: usize = 512;
pub const MAX_TOKENS: usize = 8;
pub const VOCAB_SIZE: usize = 12;

pub static VOCABULARY: [&str; VOCAB_SIZE] = [
    "hello", "routing", "sattvic", "isolated", "integrity", "execution",
    "stable", "fano", "agent", "system", "secure", "quantum"
];

// Default pre-aligned 8D E8 centroids fitted using teacher SGD
static DEFAULT_CODEBOOK_COORDINATES: [[i32; 8]; VOCAB_SIZE] = [
    [  2,   0,   0,   0,   2,   0,   0,   0], // hello
    [  0,   2,   2,   0,   0,   2,   2,   0], // routing
    [  1,   1,   1,   1,   1,   1,   1,   1], // sattvic
    [ -2,   2,   0,   0,  -2,   2,   0,   0], // isolated
    [  0,   0,   4,   0,   0,   0,   4,   0], // integrity
    [  2,  -2,   2,  -2,   2,  -2,   2,  -2], // execution
    [  0,   0,   0,   0,   0,   0,   0,   0], // stable
    [  3,   1,   1,   1,  -1,  -1,  -1,  -1], // fano
    [  1,   3,   1,   1,   1,  -3,   1,   1], // agent
    [ -1,  -1,   3,   1,  -1,  -1,   3,   1], // system
    [  2,   2,   2,   2,  -2,  -2,  -2,  -2], // secure
    [  1,   1,   1,   3,  -1,  -1,  -1,  -3], // quantum
];

// Pre-trained 8x512 projection matrix generated by PyTorch trainer
static PRE_TRAINED_PROJECTION_MATRIX: [[i16; 512]; 8] = [
    [-86, 7008, 9771, -2292, -6381, 550, -424, 3884, -3431, -74, 2325, 1921, -4388, -7424, -1681, -1447, -1593, -5494, 5128, -1628, 4701, -7032, -1749, 7674, 2851, 3228, -2049, -279, -3150, 1854, [...] 
    [2945, -633, -5188, -1806, 3702, -1867, 1133, 4563, -4511, -3980, -318, 4849, 2470, 1551, 9173, 3162, -4991, 8642, -4704, 2501, -5006, -3541, 1477, 4016, 1279, -1998, 1903, -498, 2437, -1547, [...] 
    [-1639, 971, 3132, -1614, -2191, -344, -5373, 5478, -1500, 118, -5727, -6675, -4969, 797, 1552, 626, -3482, 4400, 3158, 3608, -1970, 399, 119, -5453, -1414, -3478, 40, 2425, 2839, -988, -6593,[...]
    [-1603, 1230, 3203, -4567, 1191, 1122, 196, -4823, -3324, -347, -289, -1199, 4174, 2976, -781, 764, 2074, 1887, -2537, -1308, 3849, -6077, 1601, 2368, 1900, 5390, 807, 4448, 1631, -1366, 2006,[...]
    [4213, 397, 1965, 976, 958, 1839, 880, 492, -1875, -252, 9162, -609, -7292, -107, 1293, 5179, 370, -2831, 2876, 1513, -5458, -5253, 4882, -396, -8646, 4719, 5404, -230, 3400, 2279, -2468, 1558[...]
    [-1031, 5350, 8388, 4086, -25, -1668, 3003, 5123, 400, -1235, 1800, 3432, 2563, -458, -4095, -3973, -1580, -881, 5291, 3739, -1113, -1818, 8075, -2103, 1474, 5269, -2339, -3069, -5752, 6201, 3[...]
    [-348, 706, 349, 4089, 9167, -2900, 14665, 4225, 3460, 3401, -2085, -2128, -3210, 606, -1891, -2185, 2323, 2109, -1997, 473, 300, -217, 3411, 6120, -1368, -2102, 1307, 1351, 7106, 1219, -3850,[...]
    [-770, 2810, 1284, -1356, -3309, -3225, 4183, -579, 3144, 5877, -2284, -1507, 6422, -383, 4172, -2566, -902, -1825, -11458, 26, -1241, -5611, 1643, 571, 2179, 3600, 342, 5072, -2175, -4155, -5[...]
];

// =====================================================================
// 2. UNICODE LEXICAL PARSER
// =====================================================================

#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub struct LexicalToken {
    pub bytes: [u8; 16],
    pub len: usize,
}

impl LexicalToken {
    pub const fn new() -> Self {
        Self {
            bytes: [0u8; 16],
            len: 0,
        }
    }

    /// Shift-Add-Xor Hash for multiplier-free seed generation
    pub const fn compute_vsa_seed(&self) -> u64 {
        let mut hash: u64 = 5381;
        let mut i = 0;
        while i < self.len {
            let byte = self.bytes[i] as u64;
            hash = (hash ^ byte).wrapping_add((hash ^ byte) << 5);
            i += 1;
        }
        hash
    }
}

pub struct UnicodeLexicalParser;

impl UnicodeLexicalParser {
    pub fn parse_runs(input: &str) -> ([LexicalToken; MAX_TOKENS], usize) {
        let mut tokens = [LexicalToken::new(); MAX_TOKENS];
        let mut count = 0;
        let trimmed = input.trim();

        if trimmed.is_empty() {
            return (tokens, 0);
        }

        for word in trimmed.split_whitespace() {
            if count >= MAX_TOKENS {
                break;
            }

            let mut token = LexicalToken::new();
            let mut len = 0;

            for byte in word.bytes() {
                if len >= 16 {
                    break;
                }
                let normalized = if byte >= b'A' && byte <= b'Z' {
                    byte + 32
                } else {
                    byte
                };

                if (normalized >= b'a' && normalized <= b'z') || (normalized >= b'0' && normalized <= b'9') {
                    token.bytes[len] = normalized;
                    len += 1;
                }
            }

            if len > 0 {
                token.len = len;
                tokens[count] = token;
                count += 1;
            }
        }

        (tokens, count)
    }
}

// =====================================================================
// 3. VECTOR SYMBOLIC ARCHITECTURE (VSA) BINDING LAYER
// =====================================================================

#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub struct VsaVector {
    pub elements: [i16; VSA_DIM],
}

impl VsaVector {
    pub const fn zero() -> Self {
        Self {
            elements: [0; VSA_DIM],
        }
    }

    pub const fn deterministic_basis(seed: u64) -> Self {
        let mut elements = [0i16; VSA_DIM];
        let mut state = seed;
        let mut i = 0;

        while i < VSA_DIM {
            state = state.wrapping_add(0xf3e9_bc15_a21d_5e83);
            state = (state << 13) | (state >> 51);
            elements[i] = if (state & 1) == 1 { 1 } else { -1 };
            i += 1;
        }

        Self { elements }
    }

    pub const fn bundle(&self, other: &Self) -> Self {
        let mut elements = [0i16; VSA_DIM];
        let mut i = 0;
        while i < VSA_DIM {
            elements[i] = self.elements[i].saturating_add(other.elements[i]);
            i += 1;
        }
        Self { elements }
    }

    pub const fn project_to_8d_with_matrix(&self, matrix: &[[i16; VSA_DIM]; 8]) -> [i32; 8] {
        let mut output = [0i32; 8];
        let mut b = 0;

        while b < 8 {
            let mut dot_sum = 0i64;
            let mut i = 0;
            while i < VSA_DIM {
                dot_sum += (self.elements[i] as i64) * (matrix[b][i] as i64);
                i += 1;
            }
            output[b] = (dot_sum << 1) as i32;
            b += 1;
        }

        output
    }
}

// =====================================================================
// 4. ICOSIAN & E8 LATTICE SNAPPING GATES
// =====================================================================

pub struct E8LatticeSnapper;

impl E8LatticeSnapper {
    pub fn snap(input: [i32; 8]) -> [i32; 8] {
        let mut even_cand = [0i32; 8];
        let mut even_sum = 0i32;
        let mut even_diffs = [0i32; 8];

        for i in 0..8 {
            let val = input[i];
            let shifted = (val + 0x10000) >> 17;
            let rounded_even = shifted << 1;
            even_cand[i] = rounded_even;
            even_sum += rounded_even;
            even_diffs[i] = val - (rounded_even << 16);
        }

        if (even_sum % 4) != 0 {
            let mut best_idx = 0;
            let mut max_err = -1;
            let mut adjust_direction = 2;

            for i in 0..8 {
                let err = even_diffs[i].abs();
                if err > max_err {
                    max_err = err;
                    best_idx = i;
                    adjust_direction = if even_diffs[i] >= 0 { 2 } else { -2 };
                }
            }
            even_cand[best_idx] += adjust_direction;
        }

        let mut odd_cand = [0i32; 8];
        let mut odd_sum = 0i32;
        let mut odd_diffs = [0i32; 8];

        for i in 0..8 {
            let val = input[i];
            let shifted = val >> 17;
            let rounded_odd = (shifted << 1) + 1;
            odd_cand[i] = rounded_odd;
            odd_sum += rounded_odd;
            odd_diffs[i] = val - (rounded_odd << 16);
        }

        if (odd_sum % 4) != 0 {
            let mut best_idx = 0;
            let mut max_err = -1;
            let mut adjust_direction = 2;

            for i in 0..8 {
                let err = odd_diffs[i].abs();
                if err > max_err {
                    max_err = err;
                    best_idx = i;
                    adjust_direction = if odd_diffs[i] >= 0 { 2 } else { -2 };
                }
            }
            odd_cand[best_idx] += adjust_direction;
        }

        let mut even_dist = 0i64;
        let mut odd_dist = 0i64;

        for i in 0..8 {
            let d_even = (input[i] - (even_cand[i] << 16)) as i64;
            let d_odd = (input[i] - (odd_cand[i] << 16)) as i64;
            even_dist += (d_even * d_even) >> 16;
            odd_dist += (d_odd * d_odd) >> 16;
        }

        if even_dist <= odd_dist {
            even_cand
        } else {
            odd_cand
        }
    }
}

// =====================================================================
// 5. CORDIC S^3 HOPF ROUTING ENGINE
// =====================================================================

pub static CORDIC_TABLE: [i32; 15] = [
    25735, 15192, 8026, 4074, 2045, 1023, 511, 255, 127, 63, 31, 15, 7, 3, 1
];

pub struct CordicHopfEngine;

impl CordicHopfEngine {
    pub fn atan2(y: i32, x: i32) -> i32 {
        if x == 0 && y == 0 {
            return 0;
        }

        let mut curr_x = x;
        let mut curr_y = y;
        let mut angle = 0;

        if curr_x < 0 {
            if curr_y >= 0 {
                angle += 51471;
                curr_x = -curr_x;
                curr_y = -curr_y;
            } else {
                angle -= 51471;
                curr_x = -curr_x;
                curr_y = -curr_y;
            }
        }

        for i in 0..15 {
            let prev_x = curr_x;
            if curr_y >= 0 {
                curr_x += curr_y >> i;
                curr_y -= prev_x >> i;
                angle += CORDIC_TABLE[i];
            } else {
                curr_x -= curr_y >> i;
                curr_y += prev_x >> i;
                angle -= CORDIC_TABLE[i];
            }
        }

        angle
    }

    pub fn project_to_hopf(coords: [i32; 8]) -> (i32, i32, i32) {
        let r0 = coords[0];
        let i0 = coords[1];
        let r1 = coords[2];
        let i1 = coords[3];

        let phase_0 = Self::atan2(i0, r0);
        let phase_1 = Self::atan2(i1, r1);

        let delta = phase_1.wrapping_sub(phase_0);
        let alpha = phase_1.wrapping_add(phase_0) >> 1;

        let mag_0 = ((r0 as i64 * r0 as i64) + (i0 as i64 * i0 as i64)).isqrt() as i32;
        let mag_1 = ((r1 as i64 * r1 as i64) + (i1 as i64 * i1 as i64)).isqrt() as i32;
        let chi = Self::atan2(mag_1, mag_0);

        (chi, delta, alpha)
    }
}

// =====================================================================
// 6. MULTIPLICATION-FREE STABLE ATTENTION OPERATOR
// =====================================================================

pub struct GeometricAttention;

impl GeometricAttention {
    pub fn shift_add_exp(neg_val_q16: i32) -> i32 {
        if neg_val_q16 >= 0 {
            return 65536;
        }

        let abs_val = -neg_val_q16;
        if abs_val >= (10 << 16) {
            return 0;
        }

        let y = abs_val + (abs_val >> 1) - (abs_val >> 4) + (abs_val >> 7);
        let integer_part = y >> 16;
        let fractional_part = y & 0xFFFF;

        let linear_term = 65536 - (fractional_part >> 1);
        linear_term >> integer_part
    }

    pub fn compute_attention_weights(query_coords: [i32; 8], codebook: &[[i32; 8]; VOCAB_SIZE]) -> [i32; VOCAB_SIZE] {
        let mut raw_logits = [0i32; VOCAB_SIZE];
        let mut max_logit = i32::MIN;

        for i in 0..VOCAB_SIZE {
            let mut dot = 0i32;
            let centroid = codebook[i];
            for j in 0..8 {
                dot = dot.saturating_add(query_coords[j] * centroid[j]);
            }
            raw_logits[i] = dot;
            if dot > max_logit {
                max_logit = dot;
            }
        }

        let mut exp_sums = [0i32; VOCAB_SIZE];
        let mut sum_accum = 0i32;

        for i in 0..VOCAB_SIZE {
            let diff = (raw_logits[i] - max_logit) >> 10;
            let exp_approx = Self::shift_add_exp(diff);
            exp_sums[i] = exp_approx;
            sum_accum = sum_accum.saturating_add(exp_approx);
        }

        if sum_accum == 0 {
            sum_accum = 1;
        }

        let mut weights = [0i32; VOCAB_SIZE];
        for i in 0..VOCAB_SIZE {
            weights[i] = ((exp_sums[i] as i64 * 65536) / sum_accum as i64) as i32;
        }

        weights
    }
}

// =====================================================================
// 7. EXPOSED JS-BINDINGS / INTERACTIVE WEB ASSEMBLY WORKSPACE
// =====================================================================

#[wasm_bindgen]
pub struct InteractiveChatSession {
    context_vector: VsaVector,
    last_phase_alpha: i32,
    codebook: [[i32; 8]; VOCAB_SIZE],
    projection_matrix: [[i16; 512]; 8],
}

#[wasm_bindgen]
impl InteractiveChatSession {
    #[wasm_bindgen(constructor)]
    pub fn new() -> Self {
        Self {
            context_vector: VsaVector::zero(),
            last_phase_alpha: 0,
            codebook: DEFAULT_CODEBOOK_COORDINATES,
            projection_matrix: PRE_TRAINED_PROJECTION_MATRIX,
        }
    }

    pub fn reset(&mut self) {
        self.context_vector = VsaVector::zero();
        self.last_phase_alpha = 0;
    }

    pub fn load_custom_codebook(&mut self, flat_coords: &[i32]) -> bool {
        if flat_coords.len() != VOCAB_SIZE * 8 {
            return false;
        }
        for i in 0..VOCAB_SIZE {
            for j in 0..8 {
                self.codebook[i][j] = flat_coords[i * 8 + j];
            }
        }
        true
    }

    pub fn process_input_run(&mut self, input: &str) -> String {
        let (tokens, count) = UnicodeLexicalParser::parse_runs(input);

        if count == 0 {
            return "ERR: Invalid or non-printable ASCII runs".to_string();
        }

        for i in 0..count {
            let seed = tokens[i].compute_vsa_seed();
            let basis = VsaVector::deterministic_basis(seed);
            self.context_vector = self.context_vector.bundle(&basis);
        }

        let mut output_str = String::new();
        let mut generated_count = 0;

        let mut diag_snapped = [0i32; 8];
        let mut diag_chi = 0;
        let mut diag_delta = 0;
        let mut diag_alpha = 0;
        let mut last_word = "";

        while generated_count < 3 {
            let raw_coords = self.context_vector.project_to_8d_with_matrix(&self.projection_matrix);

            let mut warped_coords = raw_coords;
            let warp_factor = (self.last_phase_alpha as i64 * 4) as i32;
            for j in 0..8 {
                if j % 2 == 0 {
                    warped_coords[j] = warped_coords[j].saturating_add(warp_factor);
                } else {
                    warped_coords[j] = warped_coords[j].saturating_sub(warp_factor);
                }
            }

            let snapped = E8LatticeSnapper::snap(warped_coords);
            let (chi, delta, alpha) = CordicHopfEngine::project_to_hopf(snapped);
            self.last_phase_alpha = alpha;

            if generated_count == 0 {
                diag_snapped = snapped;
                diag_chi = chi;
                diag_delta = delta;
                diag_alpha = alpha;
            }

            let weights = GeometricAttention::compute_attention_weights(snapped, &self.codebook);

            let mut best_idx = 0;
            let mut max_weight = -1;
            for i in 0..VOCAB_SIZE {
                if weights[i] > max_weight {
                    max_weight = weights[i];
                    best_idx = i;
                }
            }

            let predicted_word = VOCABULARY[best_idx];
            last_word = predicted_word;
            output_str.push_str(predicted_word);
            if generated_count < 2 {
                output_str.push_str(" ");
            }
            generated_count += 1;

            let p_token = LexicalToken {
                bytes: {
                    let mut b = [0u8; 16];
                    let p_bytes = predicted_word.as_bytes();
                    let len = p_bytes.len().min(16);
                    for j in 0..len {
                        b[j] = p_bytes[j];
                    }
                    b
                },
                len: predicted_word.len(),
            };
            let p_seed = p_token.compute_vsa_seed();
            let p_basis = VsaVector::deterministic_basis(p_seed);
            self.context_vector = self.context_vector.bundle(&p_basis);
        }

        format!(
            "{{\"completion\":\"{}\", \"snapped\":[{},{},{},{},{},{},{},{}], \"chi\":{:.4}, \"delta\":{:.4}, \"alpha\":{:.4}, \"winner\":\"{}\"}}",
            output_str,
            diag_snapped[0], diag_snapped[1], diag_snapped[2], diag_snapped[3],
            diag_snapped[4], diag_snapped[5], diag_snapped[6], diag_snapped[7],
            (diag_chi as f32) / 16384.0, (diag_delta as f32) / 16384.0, (diag_alpha as f32) / 16384.0,
            last_word
        )
    }
}

// =====================================================================
// 8. BROWSER-COMPATIBLE TRAINING ADAPTER
// =====================================================================

#[wasm_bindgen]
pub struct BrowserTrainingHarness {
    codebook: [[i32; 8]; VOCAB_SIZE],
}

#[wasm_bindgen]
impl BrowserTrainingHarness {
    #[wasm_bindgen(constructor)]
    pub fn new() -> Self {
        Self {
            codebook: DEFAULT_CODEBOOK_COORDINATES,
        }
    }

    pub fn train_on_corpus(&mut self, corpus: &str, epochs: u32, learning_rate_q16: i32) -> String {
        let (tokens, count) = UnicodeLexicalParser::parse_runs(corpus);

        if count < 2 {
            return "{\"status\":\"error\", \"message\":\"Corpus must contain at least 2 valid words.\"}".to_string();
        }

        let mut total_loss = 0i64;
        let mut steps = 0;

        for _ in 0..epochs {
            for i in 0..(count - 1) {
                let current_word = tokens[i];
                let next_word = tokens[i + 1];

                let mut target_idx = None;
                let next_word_str = std::str::from_utf8(&next_word.bytes[0..next_word.len]).unwrap_or("");
                for v in 0..VOCAB_SIZE {
                    if VOCABULARY[v] == next_word_str {
                        target_idx = Some(v);
                        break;
                    }
                }

                let target_v = match target_idx {
                    Some(v) => v,
                    None => continue,
                };

                let seed = current_word.compute_vsa_seed();
                let basis = VsaVector::deterministic_basis(seed);
                let raw_coords = basis.project_to_8d_with_matrix(&PRE_TRAINED_PROJECTION_MATRIX);
                let snapped = E8LatticeSnapper::snap(raw_coords);

                let weights = GeometricAttention::compute_attention_weights(snapped, &self.codebook);

                let target_weight = weights[target_v].max(1);
                let loss = 65536 - target_weight;
                total_loss += loss as i64;
                steps += 1;

                let gradient_scalar = (loss as i64 * learning_rate_q16 as i64) >> 16;
                for j in 0..8 {
                    let grad = ((snapped[j] as i64) * gradient_scalar) >> 16;
                    self.codebook[target_v][j] = self.codebook[target_v][j].saturating_add(grad as i32);
                }
            }
        }

        let avg_loss = if steps > 0 { total_loss / steps } else { 0 };

        let mut coords_arr = String::new();
        coords_arr.push_str("[");
        for i in 0..VOCAB_SIZE {
            for j in 0..8 {
                coords_arr.push_str(&self.codebook[i][j].to_string());
                if i < VOCAB_SIZE - 1 || j < 7 {
                    coords_arr.push_str(",");
                }
            }
        }
        coords_arr.push_str("]");

        format!(
            "{{\"status\":\"success\", \"average_loss\":{:.4}, \"steps\":{}, \"updated_coordinates\":{}}}",
            (avg_loss as f32) / 65536.0,
            steps,
            coords_arr
        )
    }
}
